import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Web3OnboardProviderClient } from "./utils/web3OnboardProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Risk Analysis",
  description: "Generated by me",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Web3OnboardProviderClient>
        <body className={inter.className}>
          {children}
        </body>
      </Web3OnboardProviderClient>
    </html>
  );
}
